"""
Walmart Reports Dashboard v1.0
- 10 Walmart Marketplace reports → PostgreSQL schema `walmart`
- McKinsey-level insights with action items
- Gemini AI asks SQL questions about your data
- Same style as Sales & Traffic Dashboard (RU/UA/EN, dark/light)

Drop this file into your Streamlit `pages/` folder.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sqlalchemy import create_engine, text
from datetime import datetime, timedelta
import os
from dotenv import load_dotenv

load_dotenv()

st.set_page_config(
    page_title="Walmart Dashboard",
    page_icon="🏪",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# 🌐 ПЕРЕВОДЫ
# ============================================================

TRANSLATIONS = {
    "EN": {
        "title": "🏪 Walmart Dashboard — UDC Mower Parts",
        "refresh": "🔄 Refresh",
        "sections": "📊 Sections",
        "loading": "Loading data...",
        "no_data": "⚠️ No data. Run walmart_reports_loader first.",
        "language": "🌐 Language",
        "theme": "🎨 Theme", "dark": "Dark", "light": "Light",

        # KPI
        "total_skus": "Total SKUs",
        "gmv_30d": "GMV",
        "refunds_30d": "Refunds",
        "bb_win": "Buy Box Win",
        "cap_skus": "CAP Discount SKUs",
        "problems": "Problem SKUs",

        # Health
        "health_section": "🚨 Health Check — Action Items",
        "health_subtitle": "Issues sorted by revenue impact",
        "issue": "Issue",
        "severity": "Severity",
        "affected": "Affected",
        "impact": "Impact",
        "action": "Recommended Action",
        "owner": "Owner",

        # Buybox
        "buybox_section": "💰 Walmart CAP Discount Analysis",
        "buybox_subtitle": "How much Walmart cuts your listed price via Competitive Price Adjustment",
        "buybox_hidden_loss": "Hidden Margin Loss (per 1 unit each SKU)",
        "cap_top": "Top SKUs with Biggest Cut",
        "seller_price": "Your Price",
        "buybox_price": "BuyBox Price",
        "cut_pct": "Cut %",
        "margin_lost": "Lost $/unit",
        "sku": "SKU",
        "product": "Product",

        # Performance
        "performance_section": "📈 Item Performance",
        "performance_subtitle": "GMV, refunds, dead SKUs, negative profit",
        "dead_skus_title": "Dead SKUs (had LY sales, now zero)",
        "neg_gmv_title": "Negative GMV SKUs (refunds > sales)",
        "top_gmv": "Top 15 by GMV",
        "top_refund": "Top 10 by Refunds",
        "gmv_label": "GMV",
        "refund_label": "Refunded",
        "net_label": "Net (GMV - Refunds)",
        "ly_gmv": "Last Year GMV",
        "units": "Units",

        # Status
        "status_section": "📋 Item Status Distribution",
        "problem_skus_title": "Problem SKUs details",
        "status_col": "Status",
        "reason_col": "Reason",

        # Cancellations
        "cancel_section": "🔄 Cancellations",
        "cancel_subtitle": "All cancelled orders with reasons",
        "repeat_offenders": "SKUs cancelled more than once (restock issue)",
        "cancel_count": "Cancellations",
        "cancel_date_col": "Cancel Date",
        "reason_col_c": "Reason",

        # Loader health
        "loader_section": "⏱️ Loader Runs (last 30)",
        "report_type": "Report Type",
        "status": "Status",
        "rows_loaded": "Rows",
        "started_at": "Started At",

        # AI
        "ai_section": "🤖 AI Insights — Ask about your Walmart data",
        "ai_prompt_label": "💬 Ask anything about Walmart",
        "ai_prompt_placeholder": "Which SKUs are losing money? Why is GY21641 unpublished?",
        "ai_ask": "Ask AI",
        "ai_loading": "🤖 Gemini is analyzing...",
        "ai_error": "❌ Gemini API error",
        "ai_no_key": "⚠️ Add GEMINI_API_KEY to Streamlit Secrets",
        "ai_sql_expander": "🔎 SQL query generated by AI",
        "ai_result_expander": "📊 Data from database",
    },
    "UA": {
        "title": "🏪 Walmart Дашборд — UDC Mower Parts",
        "refresh": "🔄 Оновити",
        "sections": "📊 Розділи",
        "loading": "Завантажуємо дані...",
        "no_data": "⚠️ Немає даних. Запустіть walmart_reports_loader спочатку.",
        "language": "🌐 Мова",
        "theme": "🎨 Тема", "dark": "Темна", "light": "Світла",

        "total_skus": "Всього SKU",
        "gmv_30d": "GMV",
        "refunds_30d": "Повернення",
        "bb_win": "Buy Box Wins",
        "cap_skus": "CAP Discount SKU",
        "problems": "Проблемні SKU",

        "health_section": "🚨 Health Check — Що робити",
        "health_subtitle": "Проблеми відсортовано за впливом на виручку",
        "issue": "Проблема",
        "severity": "Критичність",
        "affected": "Кількість",
        "impact": "Вплив",
        "action": "Рекомендована дія",
        "owner": "Відповідальний",

        "buybox_section": "💰 Walmart CAP Discount",
        "buybox_subtitle": "Скільки Walmart ріже з вашої ціни через Competitive Price Adjustment",
        "buybox_hidden_loss": "Прихована втрата маржі (на 1 одиницю кожного SKU)",
        "cap_top": "Топ SKU з найбільшим урізанням",
        "seller_price": "Ваша ціна",
        "buybox_price": "BuyBox ціна",
        "cut_pct": "Cut %",
        "margin_lost": "Втрата $/од",
        "sku": "SKU",
        "product": "Товар",

        "performance_section": "📈 Продуктивність товарів",
        "performance_subtitle": "GMV, повернення, мертві SKU, негативний прибуток",
        "dead_skus_title": "Мертві SKU (продавались минулого року, зараз 0)",
        "neg_gmv_title": "SKU з негативним GMV (повернень більше ніж продажів)",
        "top_gmv": "Топ-15 за GMV",
        "top_refund": "Топ-10 за поверненнями",
        "gmv_label": "GMV",
        "refund_label": "Повернено",
        "net_label": "Чисто (GMV - Повернення)",
        "ly_gmv": "GMV минулого року",
        "units": "Одиниці",

        "status_section": "📋 Розподіл статусів товарів",
        "problem_skus_title": "Проблемні SKU — деталі",
        "status_col": "Статус",
        "reason_col": "Причина",

        "cancel_section": "🔄 Скасування замовлень",
        "cancel_subtitle": "Всі скасовані замовлення з причинами",
        "repeat_offenders": "SKU скасовано більше одного разу (проблема з запасами)",
        "cancel_count": "Скасувань",
        "cancel_date_col": "Дата скасування",
        "reason_col_c": "Причина",

        "loader_section": "⏱️ Запуски лодерів (останні 30)",
        "report_type": "Тип відчіту",
        "status": "Статус",
        "rows_loaded": "Рядків",
        "started_at": "Запущено",

        "ai_section": "🤖 AI Інсайти — Запитуй про Walmart",
        "ai_prompt_label": "💬 Запитай будь-що про Walmart",
        "ai_prompt_placeholder": "Які SKU втрачають гроші? Чому GY21641 unpublished?",
        "ai_ask": "Запитати AI",
        "ai_loading": "🤖 Gemini аналізує...",
        "ai_error": "❌ Помилка Gemini API",
        "ai_no_key": "⚠️ Додайте GEMINI_API_KEY до Streamlit Secrets",
        "ai_sql_expander": "🔎 SQL запит від AI",
        "ai_result_expander": "📊 Дані з бази",
    },
    "RU": {
        "title": "🏪 Walmart Дашборд — UDC Mower Parts",
        "refresh": "🔄 Обновить",
        "sections": "📊 Разделы",
        "loading": "Загружаем данные...",
        "no_data": "⚠️ Нет данных. Запустите walmart_reports_loader сначала.",
        "language": "🌐 Язык",
        "theme": "🎨 Тема", "dark": "Тёмная", "light": "Светлая",

        "total_skus": "Всего SKU",
        "gmv_30d": "GMV",
        "refunds_30d": "Возвраты",
        "bb_win": "Buy Box Win",
        "cap_skus": "CAP Discount SKU",
        "problems": "Проблемные SKU",

        "health_section": "🚨 Health Check — Что делать",
        "health_subtitle": "Проблемы отсортированы по влиянию на выручку",
        "issue": "Проблема",
        "severity": "Критичность",
        "affected": "Количество",
        "impact": "Влияние",
        "action": "Рекомендуемое действие",
        "owner": "Ответственный",

        "buybox_section": "💰 Walmart CAP Discount",
        "buybox_subtitle": "Сколько Walmart режет с вашей цены через Competitive Price Adjustment",
        "buybox_hidden_loss": "Скрытая потеря маржи (на 1 ед. каждого SKU)",
        "cap_top": "Топ SKU с самой большой обрезкой",
        "seller_price": "Ваша цена",
        "buybox_price": "BuyBox цена",
        "cut_pct": "Cut %",
        "margin_lost": "Потеря $/ед",
        "sku": "SKU",
        "product": "Товар",

        "performance_section": "📈 Производительность товаров",
        "performance_subtitle": "GMV, возвраты, мёртвые SKU, негативная прибыль",
        "dead_skus_title": "Мёртвые SKU (продавались в прошлом году, сейчас 0)",
        "neg_gmv_title": "SKU с негативным GMV (возвраты > продажи)",
        "top_gmv": "Топ-15 по GMV",
        "top_refund": "Топ-10 по возвратам",
        "gmv_label": "GMV",
        "refund_label": "Возвращено",
        "net_label": "Чисто (GMV - Возвраты)",
        "ly_gmv": "GMV прошлого года",
        "units": "Единицы",

        "status_section": "📋 Распределение статусов товаров",
        "problem_skus_title": "Проблемные SKU — детали",
        "status_col": "Статус",
        "reason_col": "Причина",

        "cancel_section": "🔄 Отмены заказов",
        "cancel_subtitle": "Все отменённые заказы с причинами",
        "repeat_offenders": "SKU отменяли более одного раза (проблема с запасами)",
        "cancel_count": "Отмен",
        "cancel_date_col": "Дата отмены",
        "reason_col_c": "Причина",

        "loader_section": "⏱️ Запуски лодеров (последние 30)",
        "report_type": "Тип отчёта",
        "status": "Статус",
        "rows_loaded": "Строк",
        "started_at": "Запущен",

        "ai_section": "🤖 AI Инсайты — Спроси про Walmart",
        "ai_prompt_label": "💬 Спроси любое про Walmart",
        "ai_prompt_placeholder": "Какие SKU теряют деньги? Почему GY21641 unpublished?",
        "ai_ask": "Спросить AI",
        "ai_loading": "🤖 Gemini анализирует...",
        "ai_error": "❌ Ошибка Gemini API",
        "ai_no_key": "⚠️ Добавьте GEMINI_API_KEY в Streamlit Secrets",
        "ai_sql_expander": "🔎 SQL запрос от AI",
        "ai_result_expander": "📊 Данные из БД",
    },
}

# ============================================================
# 🎨 ТЕМЫ (копия из Amazon dashboard)
# ============================================================

DARK_THEME = {
    "bg": "#0f1117", "sidebar_bg": "#0d1117",
    "card_bg": "linear-gradient(135deg, #1a1d2e, #252840)",
    "card_border": "#2d3561", "text": "#e0e0e0", "label": "#8892b0",
    "metric_val": "#7c9fff", "hr": "#21262d",
    "plot_bg": "#1a1d2e", "paper_bg": "#1a1d2e", "grid": "#2d3561",
    "template": "plotly_dark",
    "ai_bg": "#1a1d2e", "ai_border": "#2d3561",
}

LIGHT_THEME = {
    "bg": "#f5f7fa", "sidebar_bg": "#ffffff",
    "card_bg": "linear-gradient(135deg, #ffffff, #eef2ff)",
    "card_border": "#c7d2fe", "text": "#1e293b", "label": "#64748b",
    "metric_val": "#3b5bdb", "hr": "#e2e8f0",
    "plot_bg": "#ffffff", "paper_bg": "#f8fafc", "grid": "#e2e8f0",
    "template": "plotly_white",
    "ai_bg": "#eef2ff", "ai_border": "#c7d2fe",
}


def apply_theme(t):
    is_light = t['bg'] == "#f5f7fa"
    sidebar_text = "#1e293b" if is_light else "#e0e0e0"
    input_bg = "#ffffff" if is_light else "#1a1d2e"
    input_text = "#1e293b" if is_light else "#e0e0e0"

    st.markdown(f"""
    <style>
        .stApp {{ background-color: {t['bg']}; color: {t['text']}; }}
        [data-testid="metric-container"] {{
            background: {t['card_bg']};
            border: 1px solid {t['card_border']};
            border-radius: 12px; padding: 16px;
        }}
        [data-testid="stMetricValue"] {{ color: {t['metric_val']}; font-size: 1.8rem !important; }}
        [data-testid="stMetricLabel"] {{ color: {t['label']}; font-size: 0.8rem; }}
        h1, h2, h3 {{ color: {t['metric_val']} !important; }}
        [data-testid="stSidebar"] {{
            background-color: {t['sidebar_bg']} !important;
            border-right: 1px solid {t['card_border']};
        }}
        [data-testid="stSidebar"] * {{ color: {sidebar_text} !important; }}
        [data-testid="stSidebar"] .stSelectbox > div > div {{
            background-color: {input_bg} !important;
            color: {input_text} !important;
        }}
        [data-testid="stSidebar"] label {{ color: {sidebar_text} !important; }}
        p, span, div {{ color: {t['text']}; }}
        .stMarkdown p {{ color: {t['text']} !important; }}
        div[data-baseweb="popover"] ul {{ background-color: {input_bg} !important; }}
        div[data-baseweb="popover"] ul li {{
            background-color: {input_bg} !important;
            color: {input_text} !important;
        }}
        div[data-baseweb="popover"] ul li:hover {{
            background-color: {t['card_border']} !important;
        }}
        .stButton button, div.stButton > button {{
            background-color: {input_bg} !important;
            color: {input_text} !important;
            border: 1px solid {t['card_border']} !important;
        }}
        .stButton button:hover, div.stButton > button:hover {{
            border-color: {t['metric_val']} !important;
            color: {t['metric_val']} !important;
        }}
        .stButton button[kind="primary"], div.stButton > button[kind="primary"] {{
            background-color: #e03131 !important;
            color: #ffffff !important;
            border: none !important;
        }}
        .stButton button[kind="primary"]:hover {{
            background-color: #c92a2a !important;
        }}
        hr {{ border-color: {t['hr']}; }}
        .ai-box {{
            background: {t['ai_bg']};
            border: 1px solid {t['ai_border']};
            border-radius: 16px;
            padding: 24px;
            margin-top: 12px;
            line-height: 1.8;
            font-size: 1rem;
            color: {t['text']};
        }}
        .severity-crit {{
            background: rgba(224, 49, 49, 0.15);
            border-left: 4px solid #e03131;
            padding: 10px 14px;
            border-radius: 6px;
            margin: 4px 0;
        }}
        .severity-warn {{
            background: rgba(250, 176, 5, 0.12);
            border-left: 4px solid #fab005;
            padding: 10px 14px;
            border-radius: 6px;
            margin: 4px 0;
        }}
        .severity-info {{
            background: rgba(34, 139, 230, 0.10);
            border-left: 4px solid #228be6;
            padding: 10px 14px;
            border-radius: 6px;
            margin: 4px 0;
        }}
    </style>
    """, unsafe_allow_html=True)


# ============================================================
# 🗄️ БД
# ============================================================

@st.cache_resource
def get_engine():
    db_url = os.getenv("DATABASE_URL") or (
        f"postgresql://{os.getenv('DB_USER','postgres')}:"
        f"{os.getenv('DB_PASSWORD','')}@"
        f"{os.getenv('DB_HOST','localhost')}:"
        f"{os.getenv('DB_PORT','5432')}/"
        f"{os.getenv('DB_NAME','amazon')}"
    )
    if "sslmode" not in db_url:
        db_url += "?sslmode=require"
    return create_engine(db_url)


@st.cache_data(ttl=1800)
def load_walmart_data():
    """Загружает все основные Walmart таблицы одним заходом."""
    eng = get_engine()
    data = {}
    queries = {
        "items": "SELECT * FROM walmart.items",
        "performance": "SELECT * FROM walmart.item_performance",
        "inventory": "SELECT * FROM walmart.inventory_report",
        "buybox": "SELECT * FROM walmart.buybox",
        "cancellations": "SELECT * FROM walmart.cancellations ORDER BY cancel_date DESC NULLS LAST",
        "report_runs": "SELECT * FROM walmart.report_runs ORDER BY started_at DESC LIMIT 30",
    }
    try:
        with eng.connect() as conn:
            for k, q in queries.items():
                try:
                    data[k] = pd.read_sql(text(q), conn)
                except Exception:
                    data[k] = pd.DataFrame()
    except Exception as e:
        st.error(f"❌ DB Error: {e}")
        return None
    return data


# ============================================================
# 📊 KPI ROW
# ============================================================

def kpi_row(data, T):
    items = data.get("items", pd.DataFrame())
    perf = data.get("performance", pd.DataFrame())
    buybox = data.get("buybox", pd.DataFrame())

    total_skus = len(items) if not items.empty else 0
    gmv = perf["gmv"].sum() if not perf.empty and "gmv" in perf else 0
    refunds = perf["refunded_sales"].sum() if not perf.empty and "refunded_sales" in perf else 0

    bb_wins = 0
    bb_total = 0
    if not buybox.empty and "is_seller_buybox_winner" in buybox:
        bb_wins = (buybox["is_seller_buybox_winner"] == "Y").sum()
        bb_total = len(buybox)
    bb_pct = (100 * bb_wins / bb_total) if bb_total > 0 else 0

    cap_skus = 0
    if not buybox.empty and "price_diff_pct" in buybox:
        cap_skus = (buybox["price_diff_pct"].fillna(0) > 0.10).sum()

    problems = 0
    if not items.empty and "publish_status" in items:
        problems = (~items["publish_status"].isin(["PUBLISHED"])).sum()

    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric(T["total_skus"], f"{total_skus:,}")
    c2.metric(T["gmv_30d"], f"${float(gmv):,.0f}")
    c3.metric(T["refunds_30d"], f"${float(refunds):,.0f}")
    c4.metric(T["bb_win"], f"{bb_pct:.1f}%")
    c5.metric(T["cap_skus"], f"{int(cap_skus)}")
    c6.metric(T["problems"], f"{int(problems)}")


# ============================================================
# 🚨 HEALTH CHECK — McKinsey style action items
# ============================================================

def _severity_class(severity: str) -> str:
    return {"CRITICAL": "severity-crit", "WARNING": "severity-warn", "INFO": "severity-info"}.get(severity, "severity-info")


def build_action_items(data, lang: str) -> list:
    """Генерирует список action items на основе данных."""
    items = data.get("items", pd.DataFrame())
    perf = data.get("performance", pd.DataFrame())
    buybox = data.get("buybox", pd.DataFrame())
    cancel = data.get("cancellations", pd.DataFrame())

    actions = []

    # 1. SYSTEM_PROBLEM / UNPUBLISHED SKUs
    if not items.empty:
        problem_items = items[items["publish_status"].isin(["SYSTEM_PROBLEM", "UNPUBLISHED", "STAGE"])]
        if len(problem_items) > 0:
            # Group by reason
            for reason_key, sub in problem_items.groupby("status_change_reason"):
                skus = sub["sku"].tolist()
                reason_str = reason_key or "Unknown"
                if "Brand" in reason_str:
                    act_ru = "Подтвердить бренд UDC Parts в Brand Portal"
                    act_ua = "Підтвердити бренд UDC Parts в Brand Portal"
                    act_en = "Confirm UDC Parts brand in Brand Portal"
                    owner = "Женя / Операторы"
                elif "Product Type" in reason_str or "Default" in reason_str:
                    act_ru = "Назначить правильную категорию (Mower Blade / Belt) в листинге"
                    act_ua = "Призначити правильну категорію (Mower Blade / Belt) у лістингу"
                    act_en = "Set correct product category (Mower Blade / Belt)"
                    owner = "Операторы каталога"
                elif "Price" in reason_str:
                    act_ru = "Снизить цену до Walmart 'reasonable price' уровня"
                    act_ua = "Знизити ціну до Walmart 'reasonable price' рівня"
                    act_en = "Lower price to Walmart 'reasonable price' level"
                    owner = "Прайсинг"
                else:
                    act_ru = "Проверить детали в Seller Center"
                    act_ua = "Перевірити деталі в Seller Center"
                    act_en = "Check details in Seller Center"
                    owner = "Операторы"

                action_txt = {"RU": act_ru, "UA": act_ua, "EN": act_en}[lang]
                actions.append({
                    "severity": "CRITICAL",
                    "issue": reason_str,
                    "count": len(skus),
                    "impact_ru": f"Листинги {', '.join(skus[:3])}{'...' if len(skus) > 3 else ''} не могут быть куплены. Потенциал: 0 продаж.",
                    "impact_ua": f"Лістинги {', '.join(skus[:3])}{'...' if len(skus) > 3 else ''} не можуть бути куплені. Потенціал: 0 продажів.",
                    "impact_en": f"Listings {', '.join(skus[:3])}{'...' if len(skus) > 3 else ''} cannot be purchased. Potential: 0 sales.",
                    "action": action_txt,
                    "owner": owner,
                    "skus": skus,
                })

    # 2. BUYBOX CAP discount > 20%
    if not buybox.empty and "price_diff_pct" in buybox:
        heavy_cut = buybox[buybox["price_diff_pct"].fillna(0) > 0.20]
        if len(heavy_cut) > 0:
            total_loss = (heavy_cut["seller_item_price"] - heavy_cut["buybox_item_price"]).sum()
            actions.append({
                "severity": "CRITICAL",
                "issue": "CAP Discount 20%+",
                "count": len(heavy_cut),
                "impact_ru": f"Walmart режет цену на {len(heavy_cut)} SKU более чем на 20%. Скрытая потеря маржи: ${float(total_loss):.2f}/ед.",
                "impact_ua": f"Walmart ріже ціну на {len(heavy_cut)} SKU більше ніж на 20%. Прихована втрата маржі: ${float(total_loss):.2f}/од.",
                "impact_en": f"Walmart cuts price on {len(heavy_cut)} SKUs by more than 20%. Hidden margin loss: ${float(total_loss):.2f}/unit.",
                "action": {
                    "RU": "Поднять Min Allowed Price или цену листинга на 15-20%",
                    "UA": "Підняти Min Allowed Price або ціну лістингу на 15-20%",
                    "EN": "Raise Min Allowed Price or listing price by 15-20%"
                }[lang],
                "owner": "Прайсинг / Роман",
                "skus": heavy_cut["sku"].tolist(),
            })

    # 3. Medium CAP discount 10-20%
    if not buybox.empty and "price_diff_pct" in buybox:
        med_cut = buybox[
            (buybox["price_diff_pct"].fillna(0) > 0.10) &
            (buybox["price_diff_pct"].fillna(0) <= 0.20)
        ]
        if len(med_cut) > 0:
            total_loss = (med_cut["seller_item_price"] - med_cut["buybox_item_price"]).sum()
            actions.append({
                "severity": "WARNING",
                "issue": "CAP Discount 10-20%",
                "count": len(med_cut),
                "impact_ru": f"{len(med_cut)} SKU теряют 10-20% маржи скрыто. Общая потеря: ${float(total_loss):.2f}/ед.",
                "impact_ua": f"{len(med_cut)} SKU втрачають 10-20% маржі приховано. Загальна втрата: ${float(total_loss):.2f}/од.",
                "impact_en": f"{len(med_cut)} SKUs losing 10-20% margin hidden. Total: ${float(total_loss):.2f}/unit.",
                "action": {
                    "RU": "Проверить конкурентов и пересмотреть Min Price",
                    "UA": "Перевірити конкурентів і переглянути Min Price",
                    "EN": "Check competitors and review Min Price"
                }[lang],
                "owner": "Прайсинг",
                "skus": med_cut["sku"].tolist(),
            })

    # 4. Negative GMV SKUs
    if not perf.empty and "gmv" in perf and "refunded_sales" in perf:
        neg = perf[
            (perf["gmv"].fillna(0) < 0) |
            ((perf["refunded_sales"].fillna(0) > 0) &
             (perf["gmv"].fillna(0) - perf["refunded_sales"].fillna(0) < 0))
        ]
        if len(neg) > 0:
            total_loss = (neg["gmv"].fillna(0) - neg["refunded_sales"].fillna(0)).sum()
            actions.append({
                "severity": "CRITICAL",
                "issue": "Negative GMV",
                "count": len(neg),
                "impact_ru": f"{len(neg)} SKU приносят чистый убыток из-за возвратов. Сумма: ${float(total_loss):.2f}",
                "impact_ua": f"{len(neg)} SKU приносять чистий збиток через повернення. Сума: ${float(total_loss):.2f}",
                "impact_en": f"{len(neg)} SKUs bringing net loss due to refunds. Amount: ${float(total_loss):.2f}",
                "action": {
                    "RU": "Поставить на паузу, проверить отзывы и фото реальных возвратов",
                    "UA": "Поставити на паузу, перевірити відгуки та фото реальних повернень",
                    "EN": "Pause listings, check reviews and returned-product photos"
                }[lang],
                "owner": "Операторы / Контент",
                "skus": neg["sku"].tolist(),
            })

    # 5. Dead SKUs (had LY sales, now 0)
    if not perf.empty and "gmv" in perf and "total_ly_gmv" in perf:
        dead = perf[
            (perf["gmv"].fillna(0) == 0) &
            (perf["total_ly_gmv"].fillna(0) > 0)
        ]
        if len(dead) > 0:
            ly_potential = dead["total_ly_gmv"].sum()
            actions.append({
                "severity": "WARNING",
                "issue": "Dead SKUs (had LY revenue)",
                "count": len(dead),
                "impact_ru": f"{len(dead)} SKU продавались год назад, сейчас 0. Потенциал возврата: ${float(ly_potential):,.0f}",
                "impact_ua": f"{len(dead)} SKU продавались рік тому, зараз 0. Потенціал повернення: ${float(ly_potential):,.0f}",
                "impact_en": f"{len(dead)} SKUs sold last year, now 0. Recovery potential: ${float(ly_potential):,.0f}",
                "action": {
                    "RU": "Ревью листингов: обновить фото, описание, ключевые слова или снять",
                    "UA": "Ревью лістингів: оновити фото, опис, ключові слова або зняти",
                    "EN": "Listing review: update photos, copy, keywords, or remove"
                }[lang],
                "owner": "Контент / Анна (PPC)",
                "skus": dead["sku"].tolist()[:10],
            })

    # 6. Repeat cancellations
    if not cancel.empty and "catalog_item_id" in cancel:
        rep = cancel.groupby("catalog_item_id").size().reset_index(name="cnt")
        rep = rep[rep["cnt"] > 1]
        if len(rep) > 0:
            actions.append({
                "severity": "WARNING",
                "issue": "Repeat Out-of-Stock cancellations",
                "count": len(rep),
                "impact_ru": f"{len(rep)} SKU имеют повторные отмены. Покупатели недовольны, метрики аккаунта страдают.",
                "impact_ua": f"{len(rep)} SKU мають повторні скасування. Покупці незадоволені, метрики акаунту страждають.",
                "impact_en": f"{len(rep)} SKUs with repeat cancellations. Customers unhappy, account metrics suffer.",
                "action": {
                    "RU": "Срочно пополнить запас этих SKU или выставить quantity_available=0",
                    "UA": "Терміново поповнити запас цих SKU або виставити quantity_available=0",
                    "EN": "Urgently restock these SKUs or set quantity_available=0"
                }[lang],
                "owner": "Логистика / Liubov",
                "skus": rep["catalog_item_id"].tolist(),
            })

    # Sort: CRITICAL first, then by affected count
    sev_order = {"CRITICAL": 0, "WARNING": 1, "INFO": 2}
    actions.sort(key=lambda a: (sev_order.get(a["severity"], 3), -a["count"]))
    return actions


def render_health_check(data, T, theme, lang):
    st.markdown(f"### {T['health_section']}")
    st.caption(T['health_subtitle'])

    actions = build_action_items(data, lang)

    if not actions:
        st.success("✅ All clear — no critical issues detected.")
        return

    impact_key = f"impact_{lang.lower()}"

    for act in actions:
        cls = _severity_class(act["severity"])
        impact = act.get(impact_key, act.get("impact_en", ""))

        sev_emoji = {"CRITICAL": "🔴", "WARNING": "🟡", "INFO": "🔵"}.get(act["severity"], "⚪")

        st.markdown(f"""
        <div class="{cls}">
            <div style="display:flex; justify-content:space-between; align-items:center;">
                <div>
                    <strong style="font-size:1.05rem;">{sev_emoji} {act['issue']}</strong>
                    &nbsp;·&nbsp; <span style="opacity:0.8;">{T['affected']}: <b>{act['count']}</b></span>
                </div>
                <div style="opacity:0.6; font-size:0.85rem;">👤 {act['owner']}</div>
            </div>
            <div style="margin-top:6px; opacity:0.9;">{impact}</div>
            <div style="margin-top:8px;">
                <strong>→ {T['action']}:</strong> {act['action']}
            </div>
        </div>
        """, unsafe_allow_html=True)

        # Expandable: SKU list
        if act.get("skus"):
            with st.expander(f"🔽 SKU list ({len(act['skus'])})"):
                st.code("\n".join(act["skus"]), language=None)


# ============================================================
# 💰 BUYBOX CAP DISCOUNT
# ============================================================

def render_buybox(data, T, theme):
    buybox = data.get("buybox", pd.DataFrame())
    if buybox.empty:
        return

    st.markdown(f"### {T['buybox_section']}")
    st.caption(T["buybox_subtitle"])

    # KPI строка
    cut_skus = buybox[buybox["price_diff_pct"].fillna(0) > 0.05]
    total_loss = (cut_skus["seller_item_price"] - cut_skus["buybox_item_price"]).sum()

    c1, c2, c3 = st.columns(3)
    c1.metric("Cut SKUs (5%+)", f"{len(cut_skus)}")
    c2.metric("Cut SKUs (10%+)", f"{(buybox['price_diff_pct'].fillna(0) > 0.10).sum()}")
    c3.metric(T["buybox_hidden_loss"], f"${float(total_loss):.2f}")

    # Топ урезания
    st.markdown(f"#### {T['cap_top']}")
    top = cut_skus.nlargest(20, "price_diff_pct")[
        ["sku", "product_name", "seller_item_price", "buybox_item_price", "price_diff_pct", "is_seller_buybox_winner"]
    ].copy()

    top["margin_lost"] = (top["seller_item_price"] - top["buybox_item_price"]).round(2)
    top["price_diff_pct"] = (top["price_diff_pct"] * 100).round(1)
    top = top.rename(columns={
        "sku": T["sku"],
        "product_name": T["product"],
        "seller_item_price": T["seller_price"],
        "buybox_item_price": T["buybox_price"],
        "price_diff_pct": T["cut_pct"],
        "is_seller_buybox_winner": "BB",
        "margin_lost": T["margin_lost"],
    })

    # Truncate product names
    top[T["product"]] = top[T["product"]].astype(str).str[:50]

    st.dataframe(
        top,
        use_container_width=True,
        height=400,
        column_config={
            T["seller_price"]: st.column_config.NumberColumn(format="$%.2f"),
            T["buybox_price"]: st.column_config.NumberColumn(format="$%.2f"),
            T["margin_lost"]: st.column_config.NumberColumn(format="$%.2f"),
            T["cut_pct"]: st.column_config.ProgressColumn(format="%.1f%%", min_value=0, max_value=30),
        }
    )

    # Bar chart
    if len(top) > 0:
        fig = px.bar(
            top.head(15).sort_values(T["cut_pct"]),
            x=T["cut_pct"],
            y=T["sku"],
            orientation='h',
            color=T["cut_pct"],
            color_continuous_scale=[[0, "#faa"], [0.5, "#e03131"], [1, "#a00"]],
            title=T["cap_top"],
        )
        fig.update_layout(
            height=400, template=theme["template"],
            paper_bgcolor=theme["paper_bg"], plot_bgcolor=theme["plot_bg"],
            showlegend=False, coloraxis_showscale=False,
            margin=dict(l=0, r=0, t=40, b=0),
        )
        st.plotly_chart(fig, use_container_width=True)


# ============================================================
# 📈 PERFORMANCE
# ============================================================

def render_performance(data, T, theme):
    perf = data.get("performance", pd.DataFrame())
    if perf.empty:
        return

    st.markdown(f"### {T['performance_section']}")
    st.caption(T["performance_subtitle"])

    # Dead SKUs
    dead = perf[(perf["gmv"].fillna(0) == 0) & (perf["total_ly_gmv"].fillna(0) > 0)]
    if len(dead) > 0:
        st.markdown(f"#### 💀 {T['dead_skus_title']} — {len(dead)}")
        d = dead[["sku", "product_name", "total_ly_gmv", "product_level_pageviews"]].copy()
        d["product_name"] = d["product_name"].astype(str).str[:60]
        d = d.rename(columns={
            "sku": T["sku"],
            "product_name": T["product"],
            "total_ly_gmv": T["ly_gmv"],
            "product_level_pageviews": "Pageviews",
        })
        d = d.sort_values(T["ly_gmv"], ascending=False)
        st.dataframe(d, use_container_width=True, height=300,
            column_config={T["ly_gmv"]: st.column_config.NumberColumn(format="$%.2f")})

    # Negative GMV
    neg = perf[
        (perf["gmv"].fillna(0) < 0) |
        ((perf["refunded_sales"].fillna(0) > 0) &
         (perf["gmv"].fillna(0) - perf["refunded_sales"].fillna(0) < 0))
    ]
    if len(neg) > 0:
        st.markdown(f"#### 📉 {T['neg_gmv_title']} — {len(neg)}")
        n = neg[["sku", "product_name", "gmv", "refunded_sales"]].copy()
        n["net"] = (n["gmv"].fillna(0) - n["refunded_sales"].fillna(0)).round(2)
        n["product_name"] = n["product_name"].astype(str).str[:60]
        n = n.rename(columns={
            "sku": T["sku"],
            "product_name": T["product"],
            "gmv": T["gmv_label"],
            "refunded_sales": T["refund_label"],
            "net": T["net_label"],
        })
        n = n.sort_values(T["net_label"])
        st.dataframe(n, use_container_width=True, height=300,
            column_config={
                T["gmv_label"]: st.column_config.NumberColumn(format="$%.2f"),
                T["refund_label"]: st.column_config.NumberColumn(format="$%.2f"),
                T["net_label"]: st.column_config.NumberColumn(format="$%.2f"),
            })

    # Top GMV
    c1, c2 = st.columns(2)
    with c1:
        top_gmv = perf[perf["gmv"].fillna(0) > 0].nlargest(15, "gmv")
        if len(top_gmv) > 0:
            fig = px.bar(
                top_gmv.sort_values("gmv"),
                x="gmv", y="sku", orientation='h',
                title=T["top_gmv"],
                color="gmv", color_continuous_scale="Greens",
                hover_data={"product_name": True, "total_units_sold": True},
            )
            fig.update_layout(
                height=500, template=theme["template"],
                paper_bgcolor=theme["paper_bg"], plot_bgcolor=theme["plot_bg"],
                showlegend=False, coloraxis_showscale=False,
                margin=dict(l=0, r=0, t=40, b=0),
            )
            st.plotly_chart(fig, use_container_width=True)

    with c2:
        top_refund = perf[perf["refunded_sales"].fillna(0) > 0].nlargest(10, "refunded_sales")
        if len(top_refund) > 0:
            fig = px.bar(
                top_refund.sort_values("refunded_sales"),
                x="refunded_sales", y="sku", orientation='h',
                title=T["top_refund"],
                color="refunded_sales", color_continuous_scale="Reds",
                hover_data={"product_name": True, "gmv": True},
            )
            fig.update_layout(
                height=500, template=theme["template"],
                paper_bgcolor=theme["paper_bg"], plot_bgcolor=theme["plot_bg"],
                showlegend=False, coloraxis_showscale=False,
                margin=dict(l=0, r=0, t=40, b=0),
            )
            st.plotly_chart(fig, use_container_width=True)


# ============================================================
# 📋 ITEM STATUS
# ============================================================

def render_item_status(data, T, theme):
    items = data.get("items", pd.DataFrame())
    if items.empty:
        return

    st.markdown(f"### {T['status_section']}")

    c1, c2 = st.columns([1, 1.5])

    with c1:
        status_counts = items["publish_status"].fillna("NULL").value_counts().reset_index()
        status_counts.columns = ["status", "count"]
        fig = px.pie(status_counts, values="count", names="status",
                     color_discrete_sequence=["#51cf66", "#ff6b6b", "#fab005", "#868e96"])
        fig.update_layout(
            height=300, template=theme["template"],
            paper_bgcolor=theme["paper_bg"],
            margin=dict(l=0, r=0, t=20, b=0),
        )
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        probs = items[items["publish_status"].isin(["SYSTEM_PROBLEM", "UNPUBLISHED", "STAGE"])]
        if len(probs) > 0:
            st.markdown(f"#### {T['problem_skus_title']}")
            p = probs[["sku", "publish_status", "status_change_reason", "product_name"]].copy()
            p["product_name"] = p["product_name"].astype(str).str[:45]
            p = p.rename(columns={
                "sku": T["sku"],
                "publish_status": T["status_col"],
                "status_change_reason": T["reason_col"],
                "product_name": T["product"],
            })
            st.dataframe(p, use_container_width=True, height=280)


# ============================================================
# 🔄 CANCELLATIONS
# ============================================================

def render_cancellations(data, T, theme):
    cancel = data.get("cancellations", pd.DataFrame())
    if cancel.empty:
        return

    st.markdown(f"### {T['cancel_section']}")
    st.caption(T["cancel_subtitle"])

    total = len(cancel)
    by_reason = cancel["cancel_reason"].fillna("UNKNOWN").value_counts().reset_index()
    by_reason.columns = ["reason", "count"]

    c1, c2 = st.columns([1, 1])
    with c1:
        st.metric("Total Cancellations", total)
        if len(by_reason) > 0:
            st.dataframe(by_reason, use_container_width=True, hide_index=True)

    with c2:
        if "catalog_item_id" in cancel.columns:
            rep = cancel.groupby("catalog_item_id").size().reset_index(name="cnt")
            rep = rep[rep["cnt"] > 1].sort_values("cnt", ascending=False)
            if len(rep) > 0:
                st.markdown(f"#### 🚨 {T['repeat_offenders']}")
                rep = rep.rename(columns={"catalog_item_id": T["sku"], "cnt": T["cancel_count"]})
                st.dataframe(rep, use_container_width=True, hide_index=True)
            else:
                st.info("No repeat offenders ✅")


# ============================================================
# ⏱️ LOADER RUNS
# ============================================================

def render_loader_runs(data, T, theme):
    runs = data.get("report_runs", pd.DataFrame())
    if runs.empty:
        return

    st.markdown(f"### {T['loader_section']}")

    r = runs[["report_type", "status", "rows_loaded", "started_at", "error_message"]].copy()
    r = r.rename(columns={
        "report_type": T["report_type"],
        "status": T["status"],
        "rows_loaded": T["rows_loaded"],
        "started_at": T["started_at"],
        "error_message": "Error",
    })
    r[T["started_at"]] = pd.to_datetime(r[T["started_at"]], errors='coerce').dt.strftime("%Y-%m-%d %H:%M")
    st.dataframe(r, use_container_width=True, height=350, hide_index=True)


# ============================================================
# 🤖 GEMINI AI
# ============================================================

def call_gemini(prompt: str):
    import requests as req
    api_key = st.secrets.get("GEMINI_API_KEY") or os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        return None, None
    MODELS = [
        st.secrets.get("GEMINI_MODEL", "gemini-2.5-flash"),
        "gemini-2.0-flash",
        "gemini-flash-latest",
    ]
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    for model in MODELS:
        try:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
            r = req.post(url, json=payload, timeout=45)
            result = r.json()
            if "error" in result:
                continue
            if "candidates" in result and result["candidates"]:
                return result["candidates"][0]["content"]["parts"][0]["text"], model
        except Exception:
            continue
    return None, None


SCHEMA_DESCRIPTION = """
Schema: walmart

Table: walmart.items (193 rows)
Columns: sku, item_id, product_name, lifecycle_status, publish_status,
  status_change_reason, price NUMERIC, currency, buy_box_item_price,
  msrp, shipping_weight, brand, reviews_count, average_rating,
  competitor_url, competitor_price, minimum_seller_allowed_price,
  maximum_seller_allowed_price, repricer_strategy, repricer_status

Table: walmart.item_performance (137 rows, keyed by (report_date, sku))
Columns: report_date DATE, sku, product_name, department, category,
  brand, gmv NUMERIC, commission NUMERIC, gmv_minus_commission,
  aur, total_units_sold INT, cancelled_units, cancelled_sales,
  item_conversion_rate NUMERIC, total_product_visits,
  authorized_orders, authorized_units, authorized_sales,
  total_ly_gmv NUMERIC, product_level_pageviews INT,
  product_level_conversion_rate, refunded_sales NUMERIC

Table: walmart.inventory_report (193 rows)
Columns: sku, product_name, availability_code, item_condition,
  ship_node_id, quantity INT

Table: walmart.buybox (133 rows)
Columns: sku, product_name, seller_item_price NUMERIC, seller_ship_price,
  is_seller_buybox_winner CHAR(1) ('Y'/'N'),
  buybox_item_price NUMERIC, buybox_ship_price,
  price_diff_pct NUMERIC (e.g. 0.277 = 27.7% discount)

Table: walmart.cancellations
Columns: sales_order, cancel_date TIMESTAMPTZ, destination_state,
  tracking_num, carrier, catalog_item_id, cancel_reason

Table: walmart.cpa_eligibility
Columns: sku, sku_opt_in, product_name, price, ship_price

Table: walmart.ads_sem_performance (474 rows, 29 days)
Columns: report_date DATE, sku, campaign_name, ad_group_name,
  match_type, spend NUMERIC, sales NUMERIC, orders INT,
  impressions, clicks
"""


def ai_generate_sql(user_question: str, lang: str) -> str:
    prompt = f"""You are a PostgreSQL expert working with Walmart Marketplace data for UDC Mower Parts LLC (lawn mower parts seller).

{SCHEMA_DESCRIPTION}

User question: "{user_question}"

Write ONE SQL SELECT query to answer this question.
- Tables are in schema `walmart` — use full qualifier (walmart.items etc.)
- Return maximum 50 rows
- ONLY return SQL, no markdown, no explanation, no ```sql blocks
- Just pure SQL starting with SELECT"""

    sql, _ = call_gemini(prompt)
    if sql:
        sql = sql.strip().replace("```sql", "").replace("```", "").strip()
    return sql


def ai_analyze_results(user_question: str, sql: str, df_result: pd.DataFrame, lang: str):
    lang_instruction = {
        "RU": "Отвечай на русском языке.",
        "UA": "Відповідай українською мовою.",
        "EN": "Respond in English.",
    }.get(lang, "Respond in English.")

    if len(df_result) > 30:
        data_str = df_result.head(30).to_string(index=False) + f"\n... (showing 30 of {len(df_result)} rows)"
    else:
        data_str = df_result.to_string(index=False)

    prompt = f"""You are an expert Walmart Marketplace seller consultant (McKinsey-level analytics).
{lang_instruction}

User asked: "{user_question}"
SQL executed: {sql}

Query results:
{data_str}

Provide:
1. Direct answer to the question (1-2 sentences)
2. Key insights from the numbers (be specific)
3. Concrete action items — WHO does WHAT by WHEN

Use bullet points. Keep under 300 words."""

    answer, model = call_gemini(prompt)
    return answer, model


def render_ai_section(T, lang):
    st.markdown(f"### {T['ai_section']}")

    api_key = st.secrets.get("GEMINI_API_KEY", "") or os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        st.warning(T["ai_no_key"])
        with st.expander("💡 How to add"):
            st.code('GEMINI_API_KEY = "AIzaSy..."', language="toml")
            st.markdown("Streamlit Cloud → **Settings → Secrets**")
        return

    quick_q = {
        "RU": [
            "Какие SKU теряют больше всего денег из-за возвратов?",
            "Какие SKU с Walmart CAP discount больше 20%?",
            "Какие мёртвые SKU имели больше всего пейджвьюс в прошлом году?",
        ],
        "UA": [
            "Які SKU втрачають найбільше грошей через повернення?",
            "Які SKU з Walmart CAP discount більше 20%?",
            "Які мертві SKU мали найбільше pageviews минулого року?",
        ],
        "EN": [
            "Which SKUs lose the most money to refunds?",
            "Which SKUs have Walmart CAP discount above 20%?",
            "Which dead SKUs had the most pageviews last year?",
        ],
    }
    questions = quick_q.get(lang, quick_q["EN"])

    c1, c2, c3 = st.columns(3)
    b1 = c1.button(f"💸 {questions[0][:28]}...", use_container_width=True, key="q1")
    b2 = c2.button(f"🏷️ {questions[1][:28]}...", use_container_width=True, key="q2")
    b3 = c3.button(f"💀 {questions[2][:28]}...", use_container_width=True, key="q3")

    user_q = st.text_input(T["ai_prompt_label"], placeholder=T["ai_prompt_placeholder"], key="ai_input")
    ask = st.button(T["ai_ask"], type="primary", key="ai_ask")

    final_q = None
    if b1: final_q = questions[0]
    elif b2: final_q = questions[1]
    elif b3: final_q = questions[2]
    elif ask and user_q: final_q = user_q

    if final_q:
        with st.spinner("🔍 AI составляет SQL запрос..."):
            sql = ai_generate_sql(final_q, lang)
        if not sql:
            st.error(f"{T['ai_error']}: не удалось сгенерировать SQL")
            return

        with st.expander(T["ai_sql_expander"]):
            st.code(sql, language="sql")

        with st.spinner("⚡ Выполняем запрос..."):
            try:
                with get_engine().connect() as conn:
                    df_res = pd.read_sql(text(sql), conn)
            except Exception as e:
                st.error(f"❌ SQL error: {e}")
                return

        if df_res.empty:
            st.warning("⚠️ Empty result")
            return

        with st.expander(f"{T['ai_result_expander']} ({len(df_res)} rows)"):
            st.dataframe(df_res, use_container_width=True)

        with st.spinner(T["ai_loading"]):
            answer, model = ai_analyze_results(final_q, sql, df_res, lang)

        if answer:
            st.caption(f"🤖 Model: `{model}`")
            st.markdown(f'<div class="ai-box">{answer}</div>', unsafe_allow_html=True)
        else:
            st.error(T["ai_error"])


# ============================================================
# 🚀 MAIN
# ============================================================

def main():
    with st.sidebar:
        try:
            st.image(
                "https://udcparts.com/cdn/shop/files/logo.svg?v=1701894617&width=300",
                use_container_width=True
            )
        except Exception:
            st.markdown("### 🏪 UDC Parts")
        st.divider()
        lang = st.selectbox("🌐 Language / Мова / Язык", ["RU", "UA", "EN"], index=0, key="wm_lang")
        T = TRANSLATIONS[lang]
        theme_name = st.radio(T["theme"], [T["dark"], T["light"]], horizontal=True, key="wm_theme")
        theme = DARK_THEME if theme_name == T["dark"] else LIGHT_THEME
        st.divider()
        if st.button(T["refresh"], use_container_width=True, key="wm_refresh"):
            st.cache_data.clear()
            st.rerun()
        st.divider()
        st.markdown(f"### {T['sections']}")
        show_health = st.checkbox(T["health_section"], True, key="wm_s1")
        show_buybox = st.checkbox(T["buybox_section"], True, key="wm_s2")
        show_perf = st.checkbox(T["performance_section"], True, key="wm_s3")
        show_status = st.checkbox(T["status_section"], True, key="wm_s4")
        show_cancel = st.checkbox(T["cancel_section"], True, key="wm_s5")
        show_loader = st.checkbox(T["loader_section"], False, key="wm_s6")
        show_ai = st.checkbox(T["ai_section"], True, key="wm_s7")

    apply_theme(theme)

    st.markdown(f"## {T['title']}")
    st.caption(f"`walmart.*` · {datetime.now().strftime('%d.%m.%Y %H:%M')}")
    st.divider()

    with st.spinner(T["loading"]):
        data = load_walmart_data()

    if data is None or all(df.empty for df in data.values()):
        st.warning(T["no_data"])
        return

    kpi_row(data, T)
    st.divider()

    if show_health:
        render_health_check(data, T, theme, lang)
        st.divider()

    if show_buybox:
        render_buybox(data, T, theme)
        st.divider()

    if show_perf:
        render_performance(data, T, theme)
        st.divider()

    if show_status:
        render_item_status(data, T, theme)
        st.divider()

    if show_cancel:
        render_cancellations(data, T, theme)
        st.divider()

    if show_loader:
        render_loader_runs(data, T, theme)
        st.divider()

    if show_ai:
        render_ai_section(T, lang)


if __name__ == "__main__":
    main() 